base_config:
- configs/original/acoustic.yaml

dictionaries:
  zh: dictionaries/opencpop-extension.txt
all_phonemes: [AP, SP]
extra_phonemes:
merged_phoneme_groups: []
lang_phoneme_separator: [/]

datasets:
  - raw_data_dir: data/xxx1
    speaker: speaker1
    spk_id: 0
    language: zh
    test_prefixes:
    - wav1
    - wav2
    - wav3
    - wav4
    - wav5

binary_data_dir: data/xxx/binary
binarization_args:
  num_workers: 4
  allow_missing_phonemes: true

pe: rmvpe
pe_ckpt: ckpt/rmvpe/model.pt
hnsep: vr
hnsep_ckpt: ckpt/vr/model.pt
vocoder: NsfHifiGAN
vocoder_ckpt: ckpt/kouon_pc_mini_nsf-hifigan_1028/kouon_pc_mini_nsf-hifigan_1028_44100hz_512hop_128bin.ckpt

use_lang_id: false
num_lang: 1
use_spk_id: false
num_spk: 1

use_energy_embed: false
use_breathiness_embed: false
use_voicing_embed: false
use_tension_embed: false
use_key_shift_embed: true
use_speed_embed: true
augmentation_args:
  random_pitch_shifting:
    enabled: true
    range:
    - -5.0
    - 5.0
    scale: 1.75
  fixed_pitch_shifting:
    enabled: false
    targets:
    - -5.0
    - 5.0
    scale: 0.5
  random_time_stretching:
    enabled: true
    range:
    - 0.5
    - 2.0
    scale: 1.75

diffusion_type: reflow
enc_ffn_kernel_size: 3
use_rope: true
use_shallow_diffusion: true
T_start: 0.4
T_start_infer: 0.4
K_step: 300
K_step_infer: 300
backbone_type: lynxnet2
backbone_args:
  num_channels: 1024
  num_layers: 6
  kernel_size: 31
  dropout_rate: 0.0
shallow_diffusion_args:
  train_aux_decoder: true
  train_diffusion: true
  val_gt_start: false
  aux_decoder_arch: convnext
  aux_decoder_args:
    num_channels: 512
    num_layers: 6
    kernel_size: 7
    dropout_rate: 0.1
  aux_decoder_grad: 0.1
lambda_aux_mel_loss: 0.2
optimizer_args:
  optimizer_cls: modules.optimizer.muon.Muon_AdamW
  lr: 0.0006
  muon_args:
    weight_decay: 0.1
  adamw_args:
    weight_decay: 0.0
lr_scheduler_args:
  step_size: 5000
  gamma: 0.8
max_batch_frames: 50000
max_batch_size: 64
max_updates: 20ep
num_valid_plots: 1
val_with_vocoder: true
val_check_interval: 1ep
num_ckpt_keep: 50
permanent_ckpt_start: 60000
permanent_ckpt_interval: 10000
pl_trainer_devices: auto
pl_trainer_precision: bf16-mixed

lora:
  alpha: 16
  base_ckpt: finetune_ckpt_path
  enabled: true
  merge_before_export: true
  rank: 8
  target_modules:
  - ^fs2\.
  - ^diffusion\.
  train_bias: true
